from __future__ import annotations

from pathlib import Path
from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class ModelProvider(Protocol):
    async def complete(self, messages: list[dict[str, Any]], api_key: str | None = None, **kwargs: Any) -> dict[str, Any]: ...

    def capabilities(self) -> list[dict[str, Any]]: ...

    async def probe(self, api_key: str | None = None) -> dict[str, Any]: ...


@runtime_checkable
class ToolProvider(Protocol):
    async def execute(self, **kwargs: Any) -> Any: ...


@runtime_checkable
class Executor(Protocol):
    async def capabilities(self) -> Any: ...

    async def prepare(self, task_contract: Any) -> Any: ...

    async def execute_tool(self, call: Any) -> Any: ...

    async def snapshot(self, context: Any, reason: str = "executor_snapshot") -> Any: ...

    async def cancel(self, task_id: str) -> Any: ...

    async def resume(self, task_id: str) -> Any: ...

    async def cleanup(self, task_id: str) -> Any: ...


@runtime_checkable
class PermissionPolicy(Protocol):
    def authorize(self, **kwargs: Any) -> Any: ...

    def expire_task(self, task_id: str) -> None: ...


@runtime_checkable
class ContextProvider(Protocol):
    def history(self, conversation_id: int) -> list[dict[str, str]]: ...

    def stats(self, conversation_id: int) -> dict[str, Any]: ...

    def current(self, **kwargs: Any) -> dict[str, Any]: ...

    def working(self, **kwargs: Any) -> dict[str, Any]: ...

    def render(self, current: dict[str, Any], working: dict[str, Any]) -> str: ...

    def skills(self, workspace: str, prompt: str, task_id: str | None = None) -> str: ...

    async def compact(self, conversation_id: int, api_key: str | None, force: bool = False, *, task_id: str | None = None) -> dict[str, Any]: ...


@runtime_checkable
class MemoryProvider(Protocol):
    def retrieve(self, workspace: str, prompt: str) -> dict[str, Any]: ...

    def record_outcome(self, memory_ids: list[int], success: bool) -> None: ...

    def capture_experience(self, workspace: str, task_id: str, errors: list[dict[str, Any]], report: dict[str, Any], files: list[str]) -> None: ...

    def invalidate_project(self, workspace: str) -> None: ...


@runtime_checkable
class WorkspaceProvider(Protocol):
    def root(self, workspace: str) -> Path: ...

    def recover_operation(self, workspace: str, task_id: str, tool_call_id: str) -> dict[str, Any] | None: ...

    def verify_changes(self, workspace: str, task_id: str) -> dict[str, Any]: ...


@runtime_checkable
class TaskStore(Protocol):
    def conversation(self, conversation_id: int) -> dict[str, Any] | None: ...

    def task(self, task_id: str) -> dict[str, Any] | None: ...

    def start_task(self, **kwargs: Any) -> None: ...

    def resume_task(self, task_id: str, updated_at: str) -> None: ...

    def append_message(self, conversation_id: int, role: str, content: str, *, task_id: str | None = None, reasoning: str | None = None) -> None: ...

    def latest_running_repair(self, task_id: str) -> dict[str, Any] | None: ...

    def update_task(self, task_id: str, status: Any, **fields: object) -> None: ...

    def record_tool_run(self, **kwargs: Any) -> None: ...


@runtime_checkable
class Evaluator(Protocol):
    async def run(self, **kwargs: Any) -> Any: ...


@runtime_checkable
class Verifier(Protocol):
    def verify(self, task_id: str, workspace: str, plan: Any, response: str, **kwargs: Any) -> dict[str, Any]: ...

    def verify_response(self, task_id: str, response: str) -> dict[str, Any]: ...

    def finalize(self, task_id: str, report: dict[str, Any], **fields: Any) -> Any: ...


@runtime_checkable
class TraceExporter(Protocol):
    def audit(self, conversation_id: int | None, action: str, target: str, status: str, details: Any = None) -> None: ...

    def data_flow(self, **kwargs: Any) -> None: ...


@runtime_checkable
class ExtensionProvider(Protocol):
    def active_tools(self) -> tuple[list[dict[str, Any]], dict[str, Any]]: ...

    def active_profiles(self) -> list[dict[str, Any]]: ...

    def active_skills(self) -> list[dict[str, str]]: ...
